### ISSUE TITLE
As a wakala user who wants to join wakala, I want a welcome screen so that I can create a new account, login or restore an old account

### ISSUE THREAD

**Issue by CynthiaAdhiambo** [WakalaDAO/wakala-interface#1]
Acceptance Criteria:

1. User should be able to login/ register/ recover their already existing account on the login screen by entering their phone number as the login method 
2. The Phone number should be authenticated through an OTP to ensure users provide the correct numbers ( to be done whens ending or accepting a request and not during the onboarding)
3. After successful login, user should be directed to the home screen
4. If t he login/registering or recovery of the account is unsuccessful, the user should see an error message to alert them of the same

NOTE:
Ideally, phone number provided should be linked to your wakala your wallet.

**Comment by steffenkrogmann** [comment]
@CynthiaAdhiambo 

The phone number link is a good point.
Magic.link does not allow OTP just yet. But soon.

So the initial idea was to create your wallet first, and link your phone number later (because it takes about 3 minutes.

There is no way to get the time for phone number link down (because it happens on the blockchain).
Would you therefore link the phone number during onboarding/account creaion in one steop or later?

cc @Chegemartinx

**Comment by CynthiaAdhiambo** [comment]
I would think that we can use your phone number to automatically create a
wallet for you so both the login and creation of the wallet is one step

**Comment by steffenkrogmann** [comment]
Yey, but the linking of your phone number to the wallet is something else.

It is authentication (via) magic, vs. address (to receive funds).
